### ISSUE TITLE
Jira source connector only sourcing new issues

### ISSUE THREAD

**Issue by jbadeau** [apache/camel-kafka-connector#1221]
The Jira source connector seems to only publish issues created after the connector is started.

When debugging we see that the JQL query collects all our issues starting from a certain date but it only processes 1. This seems to be on purpose.

Any ideas?

**Comment by oscerd** [comment]
It's done in this way by design. https://camel.apache.org/components/latest/jira-component.html

If you want to improve it, you'll need to open a JIRA in the Apache Camel project asking for being able to consume from the beginning of time, here https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-16751?filter=allopenissues

**Comment by jbadeau** [comment]
Ok, we already added this feature? are you open to a pullrequest?

**Comment by oscerd** [comment]
Yes, but it should be against Apache Camel in the Jira component.

Il ven 25 giu 2021, 21:42 Jose Badeau ***@***.***> ha scritto:

**Comment by jbadeau** [comment]
Sure. Will do
