### ISSUE TITLE
The pre-release salesforce source connector, how does the query field work?

### ISSUE THREAD

**Issue by milkchocolate** [apache/camel-kafka-connector#1289]
With the configuration below, Kafka can receive any field changes from any entities. When does the query field step in?
![image](https://user-images.githubusercontent.com/5474821/141758360-b3b43995-16a3-44d3-9968-11d2d4e1f459.png)

**Comment by oscerd** [comment]
I think the problem is here: https://github.com/apache/camel-kamelets/blob/main/salesforce-source.kamelet.yaml#L86

It should be possible to set it in the kamelet. From the docs it should be possible to set: 

Notify for fields, options are ALL, REFERENCED, SELECT, WHERE. There are 4 enums and the value can be one of: ALL, REFERENCED, SELECT, WHERE

For the moment you'll get all the notifications.

**Comment by milkchocolate** [comment]
Hi Andrea, thanks for helping me out. Can you please also help me on the questions below?

When do we need to use the query field? 
What are the use cases for "query"?

**Comment by oscerd** [comment]
If you're using the changeEvents the query won't play any role as far as I see

https://camel.apache.org/components/3.11.x/salesforce-component.html#_change_data_capture_events

The query will join the game when you are consuming from a different topic, like for example

https://camel.apache.org/components/3.11.x/salesforce-component.html#_rest_streaming_api
