### ISSUE TITLE
AWS Kinesis source connector: error 

### ISSUE THREAD

**Issue by stebucko360** [apache/camel-kafka-connector#1391]
Im Having the following error when I use the connector:

Caused by: org.apache.camel.component.bean.MethodNotFoundException: Method with name: data() not found on bean: java.io.ByteArrayInputStream@7b75d683 of type: java.io.ByteArrayInputStream on the exchange:

I can see it has successfully connected to the kinesis stream, however when I'm sending test data into the stream this is what I get in my connector log.

Any help with the issue would be appreciated.

**Comment by stebucko360** [comment]
Issue resolved, jar file conflict was the issue

**Comment by gaddam1987** [comment]
@stebucko360  We are still facing the same issue whats the jar conflict which you fixed ?

**Comment by gaddam1987** [comment]
@stebucko360 we did fix it by changing the kamlet but still facing an issue converting ByteArrayInputStream to any subclass of `org.apache.kafka.connect.storage.Converter` because there was no default converter which can convert InputStream to bytes[] or something. Please let us know how did you fix your issue that will help us a bit

**Comment by stebucko360** [comment]
the two values I've added for ByteArray conversion are
"key.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
    "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
