### ISSUE TITLE
camel-https-kafka-connector support for multiple HTTPS endpoints

### ISSUE THREAD

**Issue by mundrusatish** [apache/camel-kafka-connector#1504]
Hello,

We have a use case to consume messages from Kafka and sink to 2 API endpoints based on condition of success of first endpoint API and sent to 2nd endpoint. 

Property for configuring the API endpoint "camel.sink.path.httpUri", however it does not have properties to allow for multiple APIs.
Can we use enterprise integration patterns in camel kafka connectors? if yes do we have any reference example project. Please share.

Do we have any OOTB conversions and transformations available in camel kafka connector project.

Thanks,
Satish

**Comment by oscerd** [comment]
If you want to use EIPs, use directly Apache Camel instead of passing through kafka connector project.

You can do that easily by consuming from a kafka endpoint.

For versions of ckc not based on Camel-Kamelets, we were providing some OOTB transformations. Since the switch to Kamelets we are not providing them anymore.

My suggestion is to move to plain Apache Camel for your use case.

**Comment by mundrusatish** [comment]
thanks @oscerd for the pointers.
the base use case is to sink to two API's at a time based on codition (des above) still not possible from ckc. Pls confirm.

**Comment by oscerd** [comment]
No, it's not possible in the way you're describing it. I think the choice of going through kafka connect is wrong in this case, with or without camel-kafka-connector.

**Comment by mundrusatish** [comment]
Thanks
