### ISSUE TITLE
Create a Google calendar example

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector#424]

**Comment by cunningt** [comment]
@oscerd Can I take this one?

**Comment by oscerd** [comment]
Sure

**Comment by jmerljak** [comment]
Any progress on this?

**Comment by oscerd** [comment]
695 has been done here https://github.com/apache/camel-kafka-connector-examples/tree/master/google-calendar-stream/google-calendar-stream-source

**Comment by jmerljak** [comment]
I see. Perhaps a note should be added to the closed task.

Anyway, is the example correct? I find the following line suspicious: `camel.source.path.index=ckc`
Shouldn't index be set to something like `events/list`?

**Comment by oscerd** [comment]
Yes, it's correct, otherwise I wouldn't commit it. Index is just a logical name.

**Comment by oscerd** [comment]
Index in calendar-stream is just a logical name. Events/list would be in the plain google calendar case

**Comment by jmerljak** [comment]
> Index in calendar-stream is just a logical name. Events/list would be in the plain google calendar case

Is there any documentation explaining the difference between 'plain' and 'stream' source connectors/components?

**Comment by oscerd** [comment]
In the components list of camel you can find more informations about the fields and examples. The behavior is the same between component and connector. I'll add some more information if i have time.

**Comment by jmerljak** [comment]
I'm still confused. From the documentation it is not clear to me how [stream connector](https://camel.apache.org/camel-kafka-connector/0.6.x/connectors/camel-google-calendar-stream-kafka-source-connector.html) differs from ['plain' one](https://camel.apache.org/camel-kafka-connector/0.6.x/connectors/camel-google-calendar-kafka-source-connector.html), or [stream component](https://camel.apache.org/components/latest/google-calendar-stream-component.html) from ['plain' component](https://camel.apache.org/components/latest/google-calendar-component.html) respectively. 

Plain one has parameters `apiName` and `methodName`. There are no such parameters on stream connector. I assumed `index` is corresponding parameter because the documentation states:
>The Google Calendar endpoint is configured using URI syntax:
`google-calendar:apiName/methodName`

and

>The Google Calendar Stream endpoint is an API based component and has additional parameters based on which API name and API method is used. The API name and API method is located in the endpoint URI as the null path parameters:
`google-calendar-stream:index`

If `index` is just a logical name, how are API name and method configured?

**Comment by oscerd** [comment]
The two components are completely different. With stream component you can only consume events from a calendar like a stream. So you'll receive a set of events on each poll. With the calendar component you can also produce events and that component has been based on the API component from camel. 

The documentation seems to be wrong anyway.

**Comment by oscerd** [comment]
The documentation should be fixed upstream.

**Comment by oscerd** [comment]
https://camel.apache.org/components/latest/google-calendar-stream-component.html

**Comment by jmerljak** [comment]
> The two components are completely different. With stream component you can only consume events from a calendar like a stream. So you'll receive a set of events on each poll. With the calendar component you can also produce events and that component has been based on the API component from camel.

Thank you, things are a bit clearer now. :)

**Comment by oscerd** [comment]
Moved to https://github.com/apache/camel-kafka-connector-examples/issues/245 for the remaining google-calendar
